### ISSUE TITLE
Implement async loading in the Token Listing tab at the Tokens page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1086]
As a user, i want to navigate to the `token transfer tab ` inside the `token page` and enter the page before the token listing get load on the screen. This page should load asynchronous, similar to the address transactions page. 

Here is an example of the page: https://blockscout.com/eth/mainnet/tokens/0xa44e5137293e855b1b7bc7e2c6f8cd796ffcb037/token_transfers

### Acceptance Criteria

- It must have a spinner evidencing that the listing is loading;
    - If an error occur during the listing loading it needs to show a message on the page;
- It needs to be loaded through Ajax;
- If there aren't token data information to show off it must show a message saying that there are no entries;
- All paginations must be through Ajax;
    - If there is no infinite scroll implemented, when the user clicks on `Older` to see more entries it needs to show the loading spinner besides the button before loading at all;
- The tab behaviour about style , listing order and quantity must be the same that is already implemented;

### Tasks
- [ ] Create function in the controller to handle the JSON requests;
- [ ] Create a javascript reducer file that will control the async requests using the (address.js, blocks.js or transactions.js) as example;
    - [ ] Check if infiniteScrollHelpers it will work without many effort;
- [ ] Create a spinner in the HTML to show before the requests;
  - [ ] Handle possible errors and show a message to the user;

**Comment by brwatanabe** [comment]
While i was testing, i noticed two unexpected behaviours:
- For some reason, CryptoKitties (CK) was the only token that didn't show any transactions after i click on "older". The page gets all blanked;
- The "older" button is showing only in the first page. After clicking it's not showing anymore.
