### ISSUE TITLE
Token Holders page should load asynchronous

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1087]
As a user, I want to navigate to the `token holders tab ` inside the `token page` allowing the overview section to load immediately and then the token holders' page will load after. This page should load asynchronous, similar to the address transactions page. 

Current page: https://blockscout.com/eth/mainnet/tokens/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/token_holders

### Acceptance Criteria

- It must have a spinner evidencing that the listing is loading;
    - If an error occurs during the listing loading it needs to show a message on the page;
- It needs to be loaded through Ajax;
- If there aren't token data information to show off it must show a message saying that there are no entries;
- All paginations must be through Ajax;
- When the user clicks on `Older` to see more entries it needs to show the loading spinner besides the button before loading at all;
- The tab behaviour about style, listing order and quantity must be the same that is already implemented;

### Tasks
- [ ] Create function in the controller to handle the JSON requests;
- [ ] Create a javascript reducer file that will control the async requests using the (address.js, blocks.js or transactions.js) as an example;
- [ ] Create a spinner in the HTML to show before the requests;
  - [ ] Handle possible errors and show a message to the user;
