### ISSUE TITLE
Decrease the initial loading time of the homepage/other pages

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1161]
The homepage load time isn't optimal and there can be an improvement here. One of the culprits might be the graph. This data can be rendered once per day and displayed quickly saving valuable time 

### Acceptance Criteria

* The Graph must be loaded asynchronously;
* The blocks listing must be loaded asynchronously without pagination;
  * The real-time feature should continue with the same behavior;
* The transactions listing must be loaded asynchronously without pagination;
  * The real-time feature should continue with the same behavior;

### Tasks

- [ ] Make the graph to be loaded async;
- [x] Make the blocks listing to be loaded async;
- [x] Make the transactions listing to be loaded async;

**Comment by igorbarinov** [comment]
any progress on the task? 
who is assigned to it?

**Comment by igorbarinov** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblockscout.com%2F

Speed Index **13.7 s** (Speed Index shows how quickly the contents of a page are visibly populated)
Time to Interactive **8.5 s** (Interactive marks the time at which the page is fully interactive.)

It's insanely slow at the moment
Which was mentioned here https://github.com/paritytech/fether/issues/311

**Comment by acravenho** [comment]
Hi Igor, there have been no free developers since this was discussed on Thursday. It's still up next, waiting for either #1268 or #1269 to close.
