### ISSUE TITLE
Overall Performance Issue Thread

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#1324]
This thread is specifically targeted at Ethereum Mainnet performance and areas that can be improved:

- [x] `newHeads` subscription from the Parity node. Many times we either do not receive the new block alert to go fetch an incoming block causing a backup for the realtime indexer. Additional logs may be required to view the performance of when the new block is started vs when it's finished indexing

- [x] internal transactions still appear to be the slow fetcher during the indexing process. We can choose to completely index them asynchronously or continue to build new rules to limit the overall number of internal transactions fetched. #1331 

- [x] Frontend load times caused by too much Javascript. This is currently being worked on in issue number #1306

- [x] Query load times on various pages. Here are a few examples #1328: 
     - https://blockscout.com/eth/mainnet/tokens/0x0d152b9ee87ebae179f64c067a966dd716c50742/token_transfers
    - https://blockscout.com/eth/mainnet/tokens/0xe7d7b37e72510309db27c460378f957b1b04bd5d/token_transfers
