### ISSUE TITLE
Transaction Details 404 page

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#38]
If a transaction does not exist yet, we should not show a standard 404 page. Instead, we should show the TX details page but with a message stating that our node hasn't picked up the transaction yet and the page will update automatically when it does.

1. If the user is on the correct route for the transaction details page but the tx hash is not found in the DB, we should show the normal transaction details page but with a message stating to please be patient while our nodes search for the transaction.
2. We should subscribe to both pending transactions and incoming blocks to find the transaction hash. 
3. If the tx hash is found, refresh the page to show either the pending state or collated state.

### Aceptance Criterias
-  Verify the TxHash in order to identify if the hash is or not valid and show to the user the correct page behavior:
    -  For invalid hashes:
        -  Show a warning message when the TxHash is invalid;
            - Message example: [Etherscan](https://etherscan.io/tx/0x0959bc78373b6c206728c3f6eff6ffd3b85b0838aa60628d6df27a53971);
    - For pending transactions:
        - Show the TxDetails Page when it's valid but doesn't exist. Suggested sentence: ```Please be patient while our nodes search for the transaction.```
        - Show a spinner for the pending transactions;
        - Show complementary information about the pending transaction process;
            - Information Example: [Etherscan](https://etherscan.io/tx/0x0959bc78373b6c206728c3f6eff6ffd3b85b0838aa60628d6df9121827a53971)

- As soon as the txHash get processed the Hash's TxDetail Page needs to be refreshed with it's current state.

### Tasks

- [x] Change controller to not redirect to the 404 page and insert the transaction hash when it is valid;
  - [x] Send the hash to the `realtime` indexer to be indexed;
  - [x] Alter view to show message of "Transaction not indexed yet."
 - [x] Subscribe to pending "transactions" and "incoming blocks" websockets so when the transaction is indexed show in the view;
- [x] When the transaction hash is invalid show message: "Transaction hash invalid."

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 75.0 DAI (75.0 USD @ $1.0/DAI)  attached to it as part of the Ethereum Community Fund via ECF Web 3.0 Infrastructure Fund fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/poanetwork/blockscout/38/1541).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/poanetwork/blockscout/38/1541).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $49,724.89 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [aj07](https://gitcoin.co/profile/aj07) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?mutate_worker_action=approve&worker=aj07) | [reject worker](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?mutate_worker_action=reject&worker=aj07))_.**

Hello,


I want to work on this. Although, I have no expereince in Exiliar, but have good knowledge on HTML/CSS and JS. And here , problem statement is on HTML/CSS. I would like to work on this. Please, do let me know, if you have any such design you want to demonstrate there.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/poanetwork/blockscout/38/1541).

**Comment by acravenho** [comment]
@aj07 Can you please provide more information on the issue? Depending upon which OS you're using and how you configured Postgres. If you installed Postgres using Homebrew you're most likely going to remove the username and password from `apps/explorer/config/dev.secret.exs`.

**Comment by aj07** [comment]
I followed https://www.postgresql.org/download/linux/ubuntu/ 

I will ping on gitter

**Comment by acravenho** [comment]
You have to provide us with the exact error message otherwise we don't have any idea how to help.

**Comment by gitcoinbot** [comment]
@aj07 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=1) | [3 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=3) | [5 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=5) | [10 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=10) | [100 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@aj07 due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/poanetwork/blockscout/38/1541) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] warning (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=1) | [3 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=3) | [5 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=5) | [10 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=10) | [100 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=100)

**Comment by aj07** [comment]
@gitcoinbot I am working on this

**Comment by brwatanabe** [comment]
@acravenho 
### Questions
- Could we use a layout similar to that one we applied to the [404 block page](https://github.com/poanetwork/blockscout/issues/36)? 
    - If necessary, we could add a spinner as for the pending txs.
    - Also, we could add more information for the user, like Etherscan does [here](https://etherscan.io/tx/0x0959bc78373b6c206728c3f6eff6ffd3b85b0838aa60628d6df9121827a53971)
- What to do with invalid hashes? Etherscan shows a message for the user as seen [here](https://etherscan.io/tx/0x0959bc78373b6c206728c3f6eff6ffd3b85b0838aa60628d6df27a53971);
- ```We should subscribe to both pending transactions and incoming blocks to find the transaction hash.```
    * In this case, should the system prioritize the searched transaction to get it processed faster than usual?

**Comment by acravenho** [comment]
1. Yes, let's use a similar layout to the 404 block page, but with a spinner :+1:  More information is always better, let's go for it.
2. Yes, let's show a similar message as Etherscan for invalid hashes.
3. Both pending and incoming blocks should be subscribed to. The realtime indexer should already be prioritizing this transaction. I'm not sure that there is much more that we can do to index it faster.

**Comment by gitcoinbot** [comment]
@aj07 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=1) | [3 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=3) | [5 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=5) | [10 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=10) | [100 days](https://gitcoin.co/issue/poanetwork/blockscout/38/1541?snooze=100)

**Comment by mkosowsk** [comment]
@GuSilverFlame please apply for work on the Gitcoin detail page and you will be approved :)

**Comment by mkosowsk** [comment]
@GuSilverFlame you have been approved, please submit your work and you will be paid out. Thanks! 👍

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 75.0 DAI (75.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@GuSilverFlame](https://gitcoin.co/profile/GuSilverFlame)



@mkosowsk please take a look at the submitted work:
* [PR](https://github.com/poanetwork/blockscout/pull/1071) by @GuSilverFlame

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/poanetwork/blockscout/38/1541)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/poanetwork/blockscout/38/1541).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $47,482.34 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 75.0 DAI (75.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @GuSilverFlame.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/poanetwork/blockscout/38/1541)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $47,407.34 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
