### ISSUE TITLE
Contributor searches for a token inside the list of token balances associated with an Address

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#424]
This issue includes a search field inside the dropdown list that is available in the Token Holdings section of the Address Details page (as developed by #50).

![screen shot 2018-07-16 at 14 55 17](https://user-images.githubusercontent.com/2921671/42774560-662e52de-8908-11e8-89ee-3c5a6067fcbe.png)

## Acceptance Criteria

- [x] When the user clicks to open the dropdown, the search field should be shown on the top of the dropdown list.
- [x] As the user starts typing, the list should be updated with the search results.

## Task Breakdown

- [x] Alter `address_token_balances/_token_balances.html.eex` to include a search field;
- [x] Access the list of token names in the Javascript;
- [x] Create a Javascript function that receives a list of names and a string and searches for this string in the list;
  - [x] The match can be any substring of the strings in the list;
  - [x] It returns the string matched;
  - [x] Filter the token list in the front-end to only the strings that match;
  - [x] See if there is a javascript lib that helps doing this;
  - [x] Hide the token type label if all tokens of that type were also hidden;
  - [x] Show the whole list when the user clears the search field;
  - [x] Clear the search field automatically when the balance dropdown closes;
  - [x] Update the list as the user types;

### Questions yet unanswered

- [x] should the token count on the dropdown change along with the search result?

**Comment by gfreh** [comment]
Hey @acravenho! I've tested it and everything seems fine. Do you want to take a look before @GuSilverFlame merges it?

**Comment by acravenho** [comment]
@gfreh Test now.
