### ISSUE TITLE
Contributor sees Read Smart Contract in the Token Details page.

### ISSUE THREAD

**Issue by gfreh** [poanetwork/blockscout#517]
### Description

As a contributor visiting the `token` details page, when the `token contract` has been verified, I want to see a "Read Smart Contract" tab so I can click on it and interact with the blockchain through read-only functions.

The tab content should be the same as for the "Read Smart Contract" tab in the Address Details page.

Example: https://kovan.etherscan.io/token/0xdab1c67232f92b7707f49c08047b96a4db7a9fc6#readContract

### Acceptance Criteria

* When the explorer user accesses the `token details` page for a verified `token contract`, she will see the "Read Smart Contract" tab.
  * If the contract has no read-only functions, the tab shouldn't be shown.

* When the user clicks on the tab, the list of read-only functions (`stateMutability: view`) without required arguments is shown with the following fields:
    * index
    * name
    * →
    * current value
        * If the value type is an address, the value should be formatted as a link
    * value type

* If the read-only function requires arguments, the following fields are shown:
    * index
    * name 
    * →
    * input field (placeholder: argument name and type)
        * If the function requires more than one argument, the input fields are listed side by side.
    * query button
    * return type (on a line below it)
    
* If the user fills a value and clicks on `query`, a section with the query response is shown with the following format:
    * `[ <name> method Response ]`
    * `<type> : <response>`
        * if the response value is an address, it should be formatted as a link
        * if the response is an error, the raised message is shown.

### Tasks

- [x] In tokens details page, display the `Read Smart Contract` tab when the `smart contract` is verified and has read-only functions;
- [x] Refactor `token` details page to separate `overview`;
- [x] Create a `token_read_smart_contract` route;
- [x] Create a `smart_contract` controller to control the actions of the `smart contract`;
- [x] Use `ajax` to render the `smart contract` functions;
- [x] Use `ajax` to interact with the read-only functions of the `smart contract`;
- [x] Refactor the `index` and` show` page of `address_read_contract_controller` so that it can be loaded via ajax;
- [x] Implement loading of ajax features;
- [x] Handle possibles errors that the request may return;
