### ISSUE TITLE
[POC] Remove duplication in controllers

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#748]
Relates to #706

As a developer, I want to remove the code duplication when I need to build a page that has the overview section and a tab menu.

Timebox of one day.

#### Path 1 

* Duplicate the routes at the `router.ex`, in order to  keep the behavior of sending the User for the page with a specific tab opened through link;
* One main controller to load the `overview` and `tab` info, this info wouldn't be loaded in others controllers (ex: `address_controller`);
* Use `ajax` to load the `tab` contents through others controllers (ex: `address_token_controller.ex`);
* Control the tab navigation using `javascript`;

### Tasks

- [x] Build a **simple** example of how this could be done and replicated to all pages in the same condition;

### Questions to be answered

- [x] Is there any other path we can follow that makes it more straightfoward to create new pages?
- [x] Is there any other projects that solved a similar problem? How?
- [x] Does this solution work with websockets?
- [x] Does the proposed scenario solves all the use cases?

**Comment by Lucasnar** [comment]
About the questions:

_Is there any other path we can follow that makes it more straightforward to create new pages?_

[This solution](https://github.com/poanetwork/blockscout/commit/8a4f8504d991346488bdad1e87cd4f340c2a078f) is more straightforward to implement than the Ajax one, since we don't need to build a new architeture in the project. We basically use resources we are already using. The result is slower for the end user though.
 
_Are there any other projects that solved a similar problem? How?_

Normally other projects will solve this using either Ajax or a front-end framework, like React or Vue. It is very common to have tabs like this in SPAs. Our application is not an SPA, but we could achieve an SPA-like behaviour for those specific pages, using Ajax. We could use a front-end framework too, but I believe that's just not worth it.

_Does this solution work with websockets?_

I'm not quite sure if the Ajax solution will work with websockets out of the box, but I believe it does. The other solution (of the centralized controller) barely changes the page behviour, so it should be fine.

 _Does the proposed scenario solves all the use cases?_

I think so. It worked well on the example and I see no reason why it wouldn't work for all use cases.

---

The above answers compare just the two solutions proposed. There is also another one we were discussing internally, and I will see if I can update the PR (https://github.com/poanetwork/blockscout/pull/765) with its description. We still haven't made our final decision on this matter.

**Comment by Lucasnar** [comment]
We ended up choosing the third proposed solution. See more on the related Pull Request (https://github.com/poanetwork/blockscout/pull/765). Just for completeness, I will answer the relevant PoC questions thinking about the third solution:

_Is there any other path we can follow that makes it more straightforward to create new pages?_

Yes. We can just create another module that holds the responsibility of building the params needed for the overviews to work, while the specific controllers only deal with their specific params. This solutions is demonstrated here: https://github.com/poanetwork/blockscout/commit/313b549268d20fefac93b0dc3476438e284f510d.

_Does this solution work with websockets?_

Yes, it should be completely compatible with everything that is already being done.

_Does the proposed scenario solves all the use cases?_

Yes, it should be completely compatible with everything that is already being done, and removes all the boiler plate duplication issue we were having.

**Comment by Lucasnar** [comment]
Given we made our final decision on this matter, I'm gonna close the issue. If you still have something to say about this, please feel free to comment here or start another issue.
