### ISSUE TITLE
Duplication of the code that defines tabs in templates

### ISSUE THREAD

**Issue by Lucasnar** [poanetwork/blockscout#776]
First task to resolve https://github.com/poanetwork/blockscout/issues/706.

As a developer, I want to have the code that creates the links to the tabs in a single partial, so I can just load it in new tabs and update it in only one place when needed. This will make both working on existing pages and creating new features easier and faster.

### Tasks

Remove the duplicated tabs code from the following pages:

- [ ] Address page;
  - [ ] Move the tabs definition to a partial;
  - [ ] Remove the tabs definition code;
  - [ ] Load the tabs definition partial;
  - [ ] Create a function to highlight the correct tab as active.
- [ ] Transaction page;
  - [ ] Move the tabs definition to a partial;
  - [ ] Remove the tabs definition code;
  - [ ] Load the tabs definition partial;
  - [ ] Create a function to highlight the correct tab as active.
- [ ] Token page.
  - [ ] Move the tabs definition to a partial;
  - [ ] Remove the tabs definition code;
  - [ ] Load the tabs definition partial;
  - [ ] Create a function to highlight the correct tab as active.

The commit https://github.com/poanetwork/blockscout/commit/8a4f8504d991346488bdad1e87cd4f340c2a078f can be used as an example of how to move the code out of the templates into a single partial; it just doesn't deal with highlighting the correct tab.

**Comment by amandasposito** [comment]
WDYT of breaking this issue into 3? One to each context?

**Comment by Lucasnar** [comment]
@amandasposito, do you mean 3 separate issues or 3 PRs?

**Comment by amandasposito** [comment]
@Lucasnar Both PR and issues, since they are separated context there are no dependencies among them and this way we can see the flow of the activities better at the board. WDYT?

**Comment by Lucasnar** [comment]
I think it is a great idea! Gonna open the three issues and close this one. 👍
