### ISSUE TITLE
Duplication of the code that defines tabs in the Transaction page

### ISSUE THREAD

**Issue by Lucasnar** [poanetwork/blockscout#778]
Related to https://github.com/poanetwork/blockscout/issues/706.

As a developer, I want to have the code that creates the links to the tabs in the Transaction page in a single partial, so I can just load it in new tabs and update it in only one place when needed. This will make both working on existing tabs of the Transaction page and creating new features easier and faster.

### Tasks

- [x] Transaction page;
  - [x] Move the tabs definition to a partial;
  - [x] Remove the tabs definition code;
  - [x] Load the tabs definition partial;
  - [x] Create a function to highlight the correct tab as active.
