### ISSUE TITLE
Duplication of the code that defines tabs in the Address page

### ISSUE THREAD

**Issue by Lucasnar** [poanetwork/blockscout#779]
Related to https://github.com/poanetwork/blockscout/issues/706.

As a developer, I want to have the code that creates the links to the tabs in the Address page in a single partial, so I can just load it in new tabs and update it in only one place when needed. This will make both working on existing tabs of the Address page and creating new features easier and faster.

### Tasks

Remove the duplicated tabs code from the following pages:

- [ ] Address page;
  - [ ] Move the tabs definition to a partial;
  - [ ] Remove the tabs definition code;
  - [ ] Load the tabs definition partial;
  - [ ] Create a function to highlight the correct tab as active.
