### ISSUE TITLE
[POC] Reset blockchain related data but still keep the user information

### ISSUE THREAD

**Issue by amandasposito** [poanetwork/blockscout#827]
As a DevOps, I want to be able to reset the blockchain related data but still keep the user information available to the explorer.

### Timebox

2 days

### Tasks
  
- [ ] Build a simple example of how this could be done;

### Questions to be answered

- [ ] How to separate user and blockchain information from the database?
    - [ ] Would it be a separate application?
    - [ ] Can we separate data using two separate databases? How?
- [ ] Is the IPFS protocol an option? How to use it?
- [ ] Will the way to separate the data make it easy in the future to interconnect the explorers?
- [ ] Would a blue/green approach with a database migration data be enough?
- [ ] How this problem is being solved by other people?

**Comment by alexgaribay** [comment]
> How to separate user and blockchain information from the database?

We've thought about this on the DockYard side. We could potentially use leverage prefixes in `Ecto.Schema`. By default, the prefix for schemas is `nil`, meaning everything falls under the `public` schema in Postgres. If we add a prefix like to user data Ecto schemas, we could make custom migration tasks that only delete things from the public PSQL schema but exclude the user data PSQL schema.

**Comment by acravenho** [comment]
@alexgaribay One of the requirements is to have all BlockScout instances have access to this data. Not only the deployed versions.

**Comment by alexgaribay** [comment]
@acravenho So this is to connect all explorers to be able to sync user data across nodes?

**Comment by acravenho** [comment]
@alexgaribay Yes, the idea is that if I verify a contract on `sokol` and it would auto verify that contract  on `core` as well because we will sync all smart contract data from this public repo every `n` minutes.  The same goes for address names. IPFS, S3 bucket, ect.. were ideas to make this happen.

**Comment by alexgaribay** [comment]
This may be worth a larger discussion. The admin tool will have several of the same issues as what's described here.

**Comment by GuSilverFlame** [comment]
after some discussion it was decided that we should go initially with the path of creating a dump file for the tables with user data

 eventually this will be replaced by postgresql's [logical replication](https://www.postgresql.org/docs/10/static/logical-replication.html) as the real solution since it will allow to have a replica of only the data that needs the replication without having to change the structure of the current database or the code
here's a [step-by-step tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-logical-replication-with-postgresql-10-on-ubuntu-18-04) on how to implement the logical replication on the database
