### ISSUE TITLE
Consolidate Block Validation Count Info.

### ISSUE THREAD

**Issue by Lokraan** [poanetwork/blockscout#875]
Relates to #768.
As a user, I want to navigate to the address page and be able to see the number of `validations` the address has performed.

Example:
https://etherscan.io/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8

### Acceptance Criteria.
* The count info for `validations` must be consolidated by address.
* There must be a task to consolidate all `validations`
* The count info must be `incremented` through async tasks.
* The `validations` count must have an approximateeand be fetched from the consolidated info.

### Tasks
- [x] Use a genserver and ets table to keep track of validations for addresses.
- [x] Create a custom mix task to run a query which consolidates the validations of each address and updates the validation count.
- [x] When a new block occurs, update the validation count for the respective validating address.

I am currently working on this issue.
