### ISSUE TITLE
Dai Chain MarketCap module

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#905]
The bridge contract address needs to be monitored in order to calculate the market cap for the Dai Chain. The chain started at $0 at block 1 and increased as new `XDAI` was minted from the bridge contract. When `XDAI` is burned the market cap should decrease by $1 to reflect this change. 

The homepage graph market cap should reflect the changes from the smart contract debits/credits.

## Acceptance Criteria
- There must be a way to config how the market cap will be obtained, whether: 
    - Using the API (from CoinMarketCap)
    - Monitoring the addresses' internal transactions to get coin mint and burn operations.
- If using the API, nothing needs to be changed.
- Otherwise, the following should take place: 
	- The graph on the home page should display the changes in the total supply for the coin in that chain, for the last month.
	- If the coin is minted, the market cap should increase. If burned, it should decrease.
	- It might be necessary to have a way to configure the price too (for the XDAI coin it will always be $1.0). 
- For the current day, the Market Cap value should be updated each 5 minutes.
- The current Market Cap value must be shown below the the graph too, next to the price.

**Comment by GuSilverFlame** [comment]
# Task Breakdown

- [ ] create module to count the total supply from transactions
  - [ ] make query to get mint events and their values from the logs
  - [ ] make query to bet burn internal transaction values
  - [ ] sum the results of each query
  - [ ] subtract total burn value from the total mint value
- [ ] create module to fetch price from coin market cap but calculate the total supply and market cap from the DB

**Comment by tmlee** [comment]
Hey @acravenho  @GuSilverFlame  if you guys are considering API to fetch supply and market cap, do take our API into consideration at https://www.coingecko.com/api

API is public and free to use, no keys needed and with little restriction to throttling.
Suggest you at least give it a try, open to hearing your feedbacks and concerns.

**Comment by acravenho** [comment]
@tmlee Thank you for the suggestion. We will take a look at your API and will create an integration for any users of BlockScout that would like to use CoinGecko's API. Having multiple price API endpoints would be great for the decentralization of the explorer. I have created issue #944.

It would also be great to see https://blockscout.com/eth/mainnet, https://blockscout.com/etc/mainnet, and https://blockscout.com/poa/core listed on BlockScout as an open source alternative block explorer.

**Comment by tmlee** [comment]
Thanks @acravenho that's good to know.

As suggested, we have also added links to those block explorers for all 3 coin pages
https://www.coingecko.com/en/coins/ethereum
https://www.coingecko.com/en/coins/ethereum-classic
https://www.coingecko.com/en/coins/poa-network

**Comment by acravenho** [comment]
@tmlee That's awesome! Looking forward to working with you guys more in the future. We'll be starting the integration soon for CoinGecko :+1:
