### ISSUE TITLE
Async task to check token supply and other metadata

### ISSUE THREAD

**Issue by acravenho** [poanetwork/blockscout#959]
Some `tokens` may have their `total supply` value changed over time. In case that happens, we won't be able to have the updated value because we only fetch that information when we are creating the token for the first time.

In order to keep the `total supply` value updated it will be necessary to fetch the data from the blockchain again because we don't know which token has been changed.

A couple options
1. Check using a cronjob at a set interval
2. Check with every token transfer

### Acceptance Criteria

* Given that we have a token already indexed with a `total supply` value when there are changes to this value in the blockchain, this value must be updated so that we can display it in the application;
* Update all metadata that have changed since the last checkout.

### Tasks

- [x] Get all cataloged tokens
- [x] Check all functions for each token
    - [x] Save valid data to database
- [x] Create a GenServer to update tokens metadata
    - [x] Create a configuration `updater_interval`;
    - [x] Rerun this operation after a given time interval.

**Comment by brwatanabe** [comment]
@acravenho 
Maybe checking at every token transfer could generate an excess of processing because it can interfere on the node performance due to the amount of requests that will be needed.
The first option suits well, but maybe we could also show the last update's timestamp together with the token total supply (it will help the users to identify if the information is old or not). We could start doing once a day (any suggestion which time is better?) set up in a config file.

WDYT?

**Comment by feliperenan** [comment]
We could enjoy this cronjob that updates the total supply to update the missing metatada. My concern in doing that is that we will make a lot of requests (one for each Token) to the Smart Contract. I don't know how it will perform in the mainnet, for instance 🙈.

Since our concern is about Token's metadata that indexer can forget when some error happens, we could add to the `Token.Fetcher` retry to fetch those metadata if they fail (similar what we did in the token balances). We could create another issue for that.

Does it make sense?
